//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diploma_IS_of_Vladkhleb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Брак
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Брак()
        {
            this.Технология_производства = new HashSet<Технология_производства>();
        }
    
        public int Код_брака { get; set; }
        public Nullable<int> Номер_документа_о_браке { get; set; }
        public Nullable<int> Код_образца { get; set; }
        public int Код_продукции { get; set; }
    
        public virtual Продукция Продукция { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Технология_производства> Технология_производства { get; set; }
        public virtual Документ_Передача_брака_в_переработку Документ_Передача_брака_в_переработку { get; set; }
    }
}
