//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diploma_IS_of_Vladkhleb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ГОСТ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ГОСТ()
        {
            this.Технология_производства = new HashSet<Технология_производства>();
        }
    
        public int Код_ГОСТа { get; set; }
        public string Наименование_ГОСТа { get; set; }
        public Nullable<int> Количество_жиров { get; set; }
        public Nullable<int> Количество_углеводов { get; set; }
        public Nullable<int> Количество_белков { get; set; }
        public Nullable<int> Наименование_пищевых_добавок { get; set; }
        public Nullable<int> Количество_каллорий { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Технология_производства> Технология_производства { get; set; }
    }
}
