//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diploma_IS_of_Vladkhleb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ_на_выпускаемую_продукцию
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заказ_на_выпускаемую_продукцию()
        {
            this.Строка_заказа_на_выпускаемую_продукцию = new HashSet<Строка_заказа_на_выпускаемую_продукцию>();
        }
    
        public int Код_заказа { get; set; }
        public string Наименование_заказа { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Строка_заказа_на_выпускаемую_продукцию> Строка_заказа_на_выпускаемую_продукцию { get; set; }
    }
}
