//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diploma_IS_of_Vladkhleb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Подготовленное_сырье
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Подготовленное_сырье()
        {
            this.Технология_производства = new HashSet<Технология_производства>();
        }
    
        public int Код_подготовленного_сырья { get; set; }
        public Nullable<int> Код_учета { get; set; }
        public Nullable<int> Номер_строки_учета_отпуска { get; set; }
        public Nullable<int> Код_заказа { get; set; }
        public Nullable<int> Номер_строки_заказа_на_выпускаемую_продукцию { get; set; }
        public string Наименование_подготовленного_сырья { get; set; }
        public Nullable<int> Код_сырья { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Технология_производства> Технология_производства { get; set; }
        public virtual Строка_учета_отпуска_сырья_в_производство Строка_учета_отпуска_сырья_в_производство { get; set; }
    }
}
