//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diploma_IS_of_Vladkhleb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Прогноз_для_нового_сырья
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Прогноз_для_нового_сырья()
        {
            this.Строка_заявки_на_поставку_сырья = new HashSet<Строка_заявки_на_поставку_сырья>();
            this.Строка_заказа_на_выпускаемую_продукцию = new HashSet<Строка_заказа_на_выпускаемую_продукцию>();
        }
    
        public int Код_сырья { get; set; }
        public Nullable<int> Количество_прогнозируемого_сырья { get; set; }
    
        public virtual Сырье Сырье { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Строка_заявки_на_поставку_сырья> Строка_заявки_на_поставку_сырья { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Строка_заказа_на_выпускаемую_продукцию> Строка_заказа_на_выпускаемую_продукцию { get; set; }
    }
}
