//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diploma_IS_of_Vladkhleb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Продукция
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Продукция()
        {
            this.Брак = new HashSet<Брак>();
            this.Образец = new HashSet<Образец>();
            this.ТОРГ_9_Упаковочный_ярлык = new HashSet<ТОРГ_9_Упаковочный_ярлык>();
        }
    
        public int Код_продукции { get; set; }
        public Nullable<int> Код_готовой_партии { get; set; }
        public Nullable<int> Количество { get; set; }
        public Nullable<int> Цена { get; set; }
        public string Ед_измерения { get; set; }
        public string НДС { get; set; }
        public Nullable<int> Масса { get; set; }
        public Nullable<System.DateTime> Дата_и_время_изготовления_пр { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Брак> Брак { get; set; }
        public virtual Готовая_партия Готовая_партия { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Образец> Образец { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ТОРГ_9_Упаковочный_ярлык> ТОРГ_9_Упаковочный_ярлык { get; set; }
    }
}
