//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diploma_IS_of_Vladkhleb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Работник
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Работник()
        {
            this.Оборудование = new HashSet<Оборудование>();
            this.ТОРГ_8_Заказ_отборочный_лист = new HashSet<ТОРГ_8_Заказ_отборочный_лист>();
            this.Технология_производства = new HashSet<Технология_производства>();
            this.Строка_графика_работ = new HashSet<Строка_графика_работ>();
            this.ТОРГ_1_Акт_о_приемке_товаров = new HashSet<ТОРГ_1_Акт_о_приемке_товаров>();
        }
    
        public int Код_работника { get; set; }
        public string ФИО_работника { get; set; }
        public string Адрес { get; set; }
        public string Телефон { get; set; }
        public Nullable<int> Код_должности { get; set; }
        public Nullable<int> Номер_бригады { get; set; }
        public string Имя_пользователя { get; set; }
        public string Пароль { get; set; }
    
        public virtual Должность Должность { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Оборудование> Оборудование { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ТОРГ_8_Заказ_отборочный_лист> ТОРГ_8_Заказ_отборочный_лист { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Технология_производства> Технология_производства { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Строка_графика_работ> Строка_графика_работ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ТОРГ_1_Акт_о_приемке_товаров> ТОРГ_1_Акт_о_приемке_товаров { get; set; }
    }
}
