//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diploma_IS_of_Vladkhleb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Строка_графика_работ
    {
        public int Номер_строки_графика_работ { get; set; }
        public Nullable<System.TimeSpan> Время_начала_смены { get; set; }
        public Nullable<System.TimeSpan> Время_окончания_смены { get; set; }
        public int Код_заказа { get; set; }
        public int Номер_строки_заказа_на_выпускаемую_продукцию { get; set; }
        public Nullable<int> Код_производственного_процесса { get; set; }
        public int Код_работника { get; set; }
    
        public virtual Работник Работник { get; set; }
        public virtual Строка_заказа_на_выпускаемую_продукцию Строка_заказа_на_выпускаемую_продукцию { get; set; }
        public virtual Технология_производства Технология_производства { get; set; }
    }
}
