//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diploma_IS_of_Vladkhleb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Строка_заказа_на_выпускаемую_продукцию
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Строка_заказа_на_выпускаемую_продукцию()
        {
            this.Строка_графика_работ = new HashSet<Строка_графика_работ>();
            this.Строка_учета_отпуска_сырья_в_производство = new HashSet<Строка_учета_отпуска_сырья_в_производство>();
        }
    
        public int Номер_строки_заказа_на_выпускаемую_продукцию { get; set; }
        public int Код_заказа { get; set; }
        public Nullable<int> Код_сырья { get; set; }
        public Nullable<int> Количество_выпускаемой_продукции { get; set; }
        public Nullable<System.DateTime> Дата_и_время_заказа_на_ВыпПрод { get; set; }
        public string Наименование_выпускаемой_продукции { get; set; }
    
        public virtual Заказ_на_выпускаемую_продукцию Заказ_на_выпускаемую_продукцию { get; set; }
        public virtual Прогноз_для_нового_сырья Прогноз_для_нового_сырья { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Строка_графика_работ> Строка_графика_работ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Строка_учета_отпуска_сырья_в_производство> Строка_учета_отпуска_сырья_в_производство { get; set; }
    }
}
