//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diploma_IS_of_Vladkhleb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Строка_учета_отпуска_сырья_в_производство
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Строка_учета_отпуска_сырья_в_производство()
        {
            this.Подготовленное_сырье = new HashSet<Подготовленное_сырье>();
        }
    
        public int Код_учета { get; set; }
        public int Номер_строки_учета_отпуска { get; set; }
        public int Код_сырья { get; set; }
        public Nullable<int> Количество_отпускаемого_сырья { get; set; }
        public int Код_заказа { get; set; }
        public int Номер_строки_заказа_на_выпускаемую_продукцию { get; set; }
        public Nullable<System.DateTime> Дата_и_время_отпуска_со_склада { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Подготовленное_сырье> Подготовленное_сырье { get; set; }
        public virtual Строка_заказа_на_выпускаемую_продукцию Строка_заказа_на_выпускаемую_продукцию { get; set; }
        public virtual Сырье Сырье { get; set; }
        public virtual Учет_отпуска_сырья_в_производство Учет_отпуска_сырья_в_производство { get; set; }
    }
}
