//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diploma_IS_of_Vladkhleb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Строка_плана_перевозок
    {
        public int Код_строки_плана_перевозок { get; set; }
        public string Адрес_назначения { get; set; }
        public Nullable<System.DateTime> Время_отъезда { get; set; }
        public Nullable<System.DateTime> Время_в_пути { get; set; }
        public Nullable<System.DateTime> Время_прибытия { get; set; }
        public int Номер_строки_ТОРГ_8 { get; set; }
    
        public virtual ТОРГ_8_Заказ_отборочный_лист ТОРГ_8_Заказ_отборочный_лист { get; set; }
    }
}
