//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diploma_IS_of_Vladkhleb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сырье
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Сырье()
        {
            this.Строка_учета_отпуска_сырья_в_производство = new HashSet<Строка_учета_отпуска_сырья_в_производство>();
            this.ТОРГ_1_Акт_о_приемке_товаров = new HashSet<ТОРГ_1_Акт_о_приемке_товаров>();
            this.Технология_производства = new HashSet<Технология_производства>();
        }
    
        public int Код_сырья { get; set; }
        public string Наименование_сырья { get; set; }
        public string Ед_измерения { get; set; }
        public int Код_поставщика { get; set; }
        public Nullable<int> Масса { get; set; }
        public Nullable<int> Количество { get; set; }
    
        public virtual Поставщик Поставщик { get; set; }
        public virtual Прогноз_для_нового_сырья Прогноз_для_нового_сырья { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Строка_учета_отпуска_сырья_в_производство> Строка_учета_отпуска_сырья_в_производство { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ТОРГ_1_Акт_о_приемке_товаров> ТОРГ_1_Акт_о_приемке_товаров { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Технология_производства> Технология_производства { get; set; }
    }
}
