//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diploma_IS_of_Vladkhleb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Технология_производства
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Технология_производства()
        {
            this.Готовая_партия = new HashSet<Готовая_партия>();
            this.Строка_графика_работ = new HashSet<Строка_графика_работ>();
        }
    
        public int Код_ГОСТа { get; set; }
        public int Код_сырья { get; set; }
        public Nullable<int> Код_подготовленного_сырья { get; set; }
        public Nullable<int> Код_оборудования { get; set; }
        public int Код_работника { get; set; }
        public Nullable<int> Код_брака { get; set; }
        public Nullable<System.TimeSpan> Время_начала_производственного_процесса { get; set; }
        public Nullable<System.TimeSpan> Время_окончания_производственного_процесса { get; set; }
        public string Наименование_производственного_процесса { get; set; }
        public int Код_производственного_процесса { get; set; }
        public Nullable<int> Код_продукции { get; set; }
    
        public virtual Брак Брак { get; set; }
        public virtual ГОСТ ГОСТ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Готовая_партия> Готовая_партия { get; set; }
        public virtual Оборудование Оборудование { get; set; }
        public virtual Подготовленное_сырье Подготовленное_сырье { get; set; }
        public virtual Работник Работник { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Строка_графика_работ> Строка_графика_работ { get; set; }
        public virtual Сырье Сырье { get; set; }
    }
}
