//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diploma_IS_of_Vladkhleb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ТОРГ_9_Упаковочный_ярлык
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ТОРГ_9_Упаковочный_ярлык()
        {
            this.ТОРГ_8_Заказ_отборочный_лист = new HashSet<ТОРГ_8_Заказ_отборочный_лист>();
        }
    
        public int Номер_строки_ТОРГ_9 { get; set; }
        public int Код_продукции { get; set; }
        public Nullable<System.DateTime> Дата_и_время_ТОРГ_9 { get; set; }
    
        public virtual Продукция Продукция { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ТОРГ_8_Заказ_отборочный_лист> ТОРГ_8_Заказ_отборочный_лист { get; set; }
    }
}
