//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diploma_IS_of_Vladkhleb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ТОРГ_1_Акт_о_приемке_товаров
    {
        public Nullable<int> Код_работника { get; set; }
        public int Номер_строки_ТОРГ_1 { get; set; }
        public int Код_сырья { get; set; }
        public Nullable<System.DateTime> Дата_и_время_ТОРГ_1 { get; set; }
    
        public virtual Работник Работник { get; set; }
        public virtual Сырье Сырье { get; set; }
    }
}
