//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diploma_IS_of_Vladkhleb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ТОРГ_8_Заказ_отборочный_лист
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ТОРГ_8_Заказ_отборочный_лист()
        {
            this.Строка_плана_перевозок = new HashSet<Строка_плана_перевозок>();
        }
    
        public int Номер_строки_ТОРГ_8 { get; set; }
        public Nullable<int> Код_продукции { get; set; }
        public Nullable<int> Код_разрешения_на_отправку { get; set; }
        public Nullable<int> Код_работника { get; set; }
        public Nullable<int> Номер_строки_ТОРГ_9 { get; set; }
        public Nullable<System.DateTime> Дата_и_время_ТОРГ_8 { get; set; }
    
        public virtual Работник Работник { get; set; }
        public virtual Разрешение_на_отправку Разрешение_на_отправку { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Строка_плана_перевозок> Строка_плана_перевозок { get; set; }
        public virtual ТОРГ_9_Упаковочный_ярлык ТОРГ_9_Упаковочный_ярлык { get; set; }
    }
}
