//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diploma_IS_of_Vladkhleb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Учет_отпуска_сырья_в_производство
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Учет_отпуска_сырья_в_производство()
        {
            this.Строка_учета_отпуска_сырья_в_производство = new HashSet<Строка_учета_отпуска_сырья_в_производство>();
        }
    
        public int Код_учета { get; set; }
        public string Наименование_учета { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Строка_учета_отпуска_сырья_в_производство> Строка_учета_отпуска_сырья_в_производство { get; set; }
    }
}
